# SPDX-FileCopyrightText: 2026 maximizzar <mail@maximizzar.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: ci
on:
  push:

jobs:
  build-disk-image-matrix:
    runs-on: nixos
    strategy:
      matrix:
        image: [ "resolverImage" ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build QCOW2 Image 
        run: |
          nix build .#${{ matrix.image }} -o result-${{ matrix.image }}     

      - name: Upload QCOW2 Artifact
        uses: forgejo/upload-artifact@v4
        with:
          name: qcow2-${{ matrix.image }}
          path: result-${{ matrix.image }}/main.qcow2
          overwrite: true

