# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  hagezi-doh = {
    pname = "hagezi-doh";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/doh.txt";
      sha256 = "sha256-qzVnCv/gzmcT1I4XCgcw7BfFJ+50aP1c7HIj21gPvsE=";
    };
    date = "2026-09-03";
  };
  hagezi-gambling = {
    pname = "hagezi-gambling";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/gambling.txt";
      sha256 = "sha256-0LhRWAHyVp8QM/q+aUnHRoth5UoypwUCa8SSuMmBWEI=";
    };
    date = "2026-09-03";
  };
  hagezi-hoster = {
    pname = "hagezi-hoster";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/hoster.txt";
      sha256 = "sha256-uJMzWRxZINICxwgPBi1R80yE1PDn+NPZ2+g5AjtpHc8=";
    };
    date = "2026-09-03";
  };
  hagezi-native-amazon = {
    pname = "hagezi-native-amazon";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.amazon.txt";
      sha256 = "sha256-j8XmfJFCqv9IJQieeYGEqhFMY4jKMjFbszMuXTHF6Ag=";
    };
    date = "2026-09-03";
  };
  hagezi-native-apple = {
    pname = "hagezi-native-apple";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.apple.txt";
      sha256 = "sha256-I95ItYsK3o8HcfrBiWVzyaITZtb6Dh8CgA+hyAu9bWY=";
    };
    date = "2026-09-03";
  };
  hagezi-native-huawei = {
    pname = "hagezi-native-huawei";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.huawei.txt";
      sha256 = "sha256-dZaC14ep1lKial1ScrIK6osK0Z1rEakr0jhbqG3cbBg=";
    };
    date = "2026-09-03";
  };
  hagezi-native-lgwebos = {
    pname = "hagezi-native-lgwebos";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.lgwebos.txt";
      sha256 = "sha256-EEUnZm1Aood/bJlTC84hVuV6VrRULk1xIqJdsfbmogA=";
    };
    date = "2026-09-03";
  };
  hagezi-native-oppo-realme = {
    pname = "hagezi-native-oppo-realme";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.oppo-realme.txt";
      sha256 = "sha256-jXHIOmSiooLLD6abRKRyPlvzAcPO79kH5MiAyoHqZS4=";
    };
    date = "2026-09-03";
  };
  hagezi-native-roku = {
    pname = "hagezi-native-roku";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.roku.txt";
      sha256 = "sha256-PZiiMbpCEMBgM95QcHNdVbiM6KzfakVweAAtv4/NJCw=";
    };
    date = "2026-09-03";
  };
  hagezi-native-samsung = {
    pname = "hagezi-native-samsung";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.samsung.txt";
      sha256 = "sha256-hoP1ScomVfZWsmqfCXajIkwa8Ufg2fw84mzmuYGDu5k=";
    };
    date = "2026-09-03";
  };
  hagezi-native-tiktok = {
    pname = "hagezi-native-tiktok";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.tiktok.extended.txt";
      sha256 = "sha256-n6nVaxfNH0hMtd5noPxHqAIOHrqko1RqGk3oSfNRxxA=";
    };
    date = "2026-09-03";
  };
  hagezi-native-vivo = {
    pname = "hagezi-native-vivo";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.vivo.txt";
      sha256 = "sha256-DfAsD27obXWQqizTST4/Tx5uiDfL5GofuH8/cGA46q4=";
    };
    date = "2026-09-03";
  };
  hagezi-native-winoffice = {
    pname = "hagezi-native-winoffice";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.winoffice.txt";
      sha256 = "sha256-3xr4UkYVjzHvil8AGcsf/ZIrL2cORkvuZGkdMNANN1U=";
    };
    date = "2026-09-03";
  };
  hagezi-native-xiaomi = {
    pname = "hagezi-native-xiaomi";
    version = "c1d35162e3f4fd8453832e052b4efddf63fe2931";
    src = fetchurl {
      url = "https://gitlab.com/hagezi/mirror/-/raw/c1d35162e3f4fd8453832e052b4efddf63fe2931/dns-blocklists/rpz/native.xiaomi.txt";
      sha256 = "sha256-HkhmxaVSzZbmga68zpyoUraZ5XqDJ8sfQCxKliL589U=";
    };
    date = "2026-09-03";
  };
}
