zone "@DOMAIN@" {
    type master;
    file "/etc/powerdns/zones/@DOMAIN@.zone";
};

zone "a.1.9.6.8.a.a.3.0.8.d.f.ip6.arpa" {
    type master;
    file "/etc/powerdns/zones/a.1.9.6.8.a.a.3.0.8.d.f.ip6.arpa.zone";
};
